  # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Complete CI/CD Process
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    ECR_REPO_NAME: 'akashjenkinsecr'
    AWS_REGION: 'ap-east-1'
    ECR_PUBLIC_REPO_URI: 'public.ecr.aws/i4d6z1a1/akashjenkinsecr'
    IMAGE_TAG: 'Latest_Image'
    AWS_ACCOUNT_ID: '705307574220'
    IMAGE_URI: "${ECR_PUBLIC_REPO_URI}:${IMAGE_TAG}"
jobs:  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install AWS CLI
        run: |
         echo "Installing AWS CLI ..."
         sudo apt update && sudo apt install -y unzip curl
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip -q awscliv2.zip
         sudo ./aws/install --update
         aws --version
          
      - name: Configure AWS Credentials
        run: |
         echo "Setting up AWS credentials for this shell session..."
         export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
         export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}}
         export AWS_REGION=${{ env.AWS_REGION }}

         #Save to ~/.aws/credentials for CLI commands to pick up
         mkdir -p ~/.aws
          cat <<EOF > ~/.aws/credentials
          [default]
          aws_access_key_id=${AWS_ACCESS_KEY_ID}
          aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
          region=${AWS_REGION}  
          EOF
        

      - name: Build with Maven
        run: |
          echo "Building Java Application"
          mvn clean package
          
      - name: Login to AWS ECR Repository
        run: |
          echo "Logging into AWS ECR Public..."
          aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws

      - name: Push Docker Image ECR
        run: |
          echo "Pushing Docker Image..."
          docker push $IMAGE_URI
          
          
          
          
              
      
    
  

 
